spring:
  application:
    name: library
  profiles:
    active: test
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
open:
  api:
    title: "API Library Document"
    version: "1.0.0"
    description: "api library document"
    serverName: "Default Server"

logging:
  level:
    com.project.library: DEBUG
