server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 123456

open:
  api:
    serverUrl: http://localhost:${server.port}
    serverName: Server TEST
    description: "API for TEST environment"
